name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
     
      - name: Install dependencies
        run: go get .
     
      - name: Build
        run: go build -v 

  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
     
      - name: Install dependencies
        run: go get .
     
      - name: Test
        run: go test -v 
  
  gofmt: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Check gofmt
        run: if [ "$(gofmt -s -d . | wc -l)" -gt 0 ]; then exit 1; fi

  golines: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: go install github.com/segmentio/golines@latest

      - name: Check golines
        run: if [ "$(golines -m 120 --dry-run . | wc -l)" -gt 0 ]; then exit 1; fi
